"use client";

import { type ReactNode, useCallback, useEffect, useState } from "react";

import { botApi } from "@/lib/api";
import type { AlertEvent, OperationalMetrics, PaperSession, Readiness, SystemVersion } from "@/types/bot";

function Card({ label, value }: { label: string; value: ReactNode }) { return <article className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold">{value ?? "--"}</p></article>; }
function statusClass(status: string) { return status === "ready" || status === "healthy" || status === "complete" ? "text-emerald-300" : status.includes("error") || status === "not_ready" ? "text-rose-300" : "text-amber-300"; }

export default function OperationsPage() {
  const [ready, setReady] = useState<Readiness | null>(null); const [version, setVersion] = useState<SystemVersion | null>(null); const [metrics, setMetrics] = useState<OperationalMetrics | null>(null); const [session, setSession] = useState<PaperSession | null>(null); const [alerts, setAlerts] = useState<AlertEvent[]>([]); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { try { const [nextReady, nextVersion, nextMetrics, nextSession, nextAlerts] = await Promise.all([botApi.systemReady(), botApi.systemVersion(), botApi.systemMetrics(), botApi.paperSession(), botApi.systemAlerts()]); setReady(nextReady); setVersion(nextVersion); setMetrics(nextMetrics); setSession(nextSession); setAlerts(nextAlerts); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operations API unavailable"); } }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 15_000); return () => window.clearInterval(timer); }, [refresh]);
  return <main className="mx-auto min-h-screen max-w-7xl px-4 py-5 sm:px-6 lg:px-8"><header className="flex items-center justify-between border-b border-slate-800 pb-5"><div><p className="text-xs font-bold tracking-[0.24em] text-cyan-400">OPERATIONS</p><h1 className="mt-1 text-2xl font-bold">SYSTEM STATUS</h1><p className="mt-2 text-sm text-amber-300">PAPER TRADING ONLY · NO REAL ORDERS</p></div><button className="rounded border border-cyan-400/60 px-3 py-2 text-sm text-cyan-200" onClick={() => void refresh()} type="button">Refresh</button></header>{error ? <p className="mt-5 rounded border border-rose-500/40 p-3 text-rose-200">{error}</p> : null}{ready && version && metrics && session ? <><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card label="Readiness" value={<span className={statusClass(ready.status)}>{ready.status.toUpperCase()}</span>} /><Card label="Environment" value={version.environment} /><Card label="Version" value={version.version} /><Card label="Session" value={session.status} /><Card label="Recovery" value={ready.health.recovery} /></section><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card label="Database" value={ready.health.database} /><Card label="Market" value={ready.health.market} /><Card label="WebSocket clients" value={metrics.active_ws_clients} /><Card label="Valid / invalid candles" value={`${metrics.valid_candles} / ${metrics.invalid_candles}`} /><Card label="Entries / closes" value={`${metrics.paper_entries} / ${metrics.paper_closes}`} /></section><section className="mt-6 rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Freshness</h2><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">{Object.entries(ready.health.freshness).map(([key, value]) => <p key={key}>{key}: <span className="text-slate-300">{value ?? "not observed"}</span></p>)}</div></section><section className="mt-6 rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-semibold">Active alerts</h2>{alerts.length ? <ul className="mt-3 space-y-2 text-sm">{alerts.map((alert) => <li className={statusClass(alert.severity)} key={alert.alert_id}>{alert.severity.toUpperCase()} · {alert.code}: {alert.message}</li>)}</ul> : <p className="mt-3 text-sm text-emerald-300">No active alerts.</p>}</section></> : <p className="mt-6 text-sm text-slate-400">Loading operational status…</p>}</main>;
}
